#!/usr/bin/env sh

spacebar -m config position top
spacebar -m config display all
spacebar -m config height 26
spacebar -m config title off

spacebar -m config padding_left 20
spacebar -m config padding_right 20
spacebar -m config spacing_left 20
spacebar -m config spacing_right 20

spacebar -m config text_font "Iosevka Fixed:Regular:12.0"
spacebar -m config icon_font "Iosevka Fixed:Regular:12.0"

spacebar -m config background_color 0xff000000
spacebar -m config foreground_color 0xffffffff

spacebar -m config power on
spacebar -m config power_icon_strip DISCHARGING CHARGING
spacebar -m config power_icon_color 0xfffeacd0
spacebar -m config battery_icon_color 0xffff8059

spacebar -m config spaces on
spacebar -m config space_icon =
spacebar -m config space_icon_color 0xffff8059
spacebar -m config spaces_for_all_displays off
spacebar -m config space_icon_strip 1 2 3 4 5 6 7 8 9 10

spacebar -m config clock on
spacebar -m config clock_icon CLOCK
spacebar -m config clock_icon_color 0xff44bc44
spacebar -m config clock_format "%R, %a %d %B"

spacebar -m config dnd on
spacebar -m config dnd_icon DND
spacebar -m config dnd_icon_color 0xffcc6666

spacebar -m config right_shell on
spacebar -m config right_shell_icon MAIL
spacebar -m config right_shell_icon_color 0xff00d3d0
spacebar -m config right_shell_command "mu find \
'flag:unread and m:/university/inbox or flag:unread and m:/gmail/inbox' \
| wc -l | tr -d '[:blank:]'"

spacebar -m config center_shell on
spacebar -m config center_shell_command "osascript $HOME/.config/spacebar/music | cat"

spacebar -m config left_shell on
spacebar -m config left_shell_icon WIFI
spacebar -m config left_shell_icon_color 0xff44bc44
spacebar -m config left_shell_command "$HOME/.config/spacebar/network"

echo "spacebar configuration loaded.."
